//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_details
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="Customer_details.Z_bapi_customer_details")]
    public interface Z_bapi_customer_details
    {
        
        // CODEGEN : La génération du contrat de message depuis l'opération Z_BAPI_CUSTOMER_CREDITDETAILS n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_bapi_customer_details:Z_BAPI_CUSTOMER_CR" +
            "EDITDETAILSRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse1 Z_BAPI_CUSTOMER_CREDITDETAILS(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_bapi_customer_details:Z_BAPI_CUSTOMER_CR" +
            "EDITDETAILSRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse1> Z_BAPI_CUSTOMER_CREDITDETAILSAsync(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_BAPI_CUSTOMER_CREDITDETAILS
    {
        
        private string cREDIT_CONTROL_AREAField;
        
        private string cUSTOMERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CREDIT_CONTROL_AREA
        {
            get
            {
                return this.cREDIT_CONTROL_AREAField;
            }
            set
            {
                this.cREDIT_CONTROL_AREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CUSTOMER
        {
            get
            {
                return this.cUSTOMERField;
            }
            set
            {
                this.cUSTOMERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_BAPI_CUSTOMER_CREDITDETAILSResponse
    {
        
        private string bLOCKEDField;
        
        private string cREDIT_CONTROLLING_AREAField;
        
        private decimal cREDIT_EXPOSUREField;
        
        private decimal cREDIT_LIMITField;
        
        private decimal cREDIT_LIMIT_USEDField;
        
        private string cUSTOMER_NUMBERField;
        
        private decimal rECEIVABLESField;
        
        private decimal sALES_VALUEField;
        
        private decimal sPECIAL_LIABILITIESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BLOCKED
        {
            get
            {
                return this.bLOCKEDField;
            }
            set
            {
                this.bLOCKEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CREDIT_CONTROLLING_AREA
        {
            get
            {
                return this.cREDIT_CONTROLLING_AREAField;
            }
            set
            {
                this.cREDIT_CONTROLLING_AREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal CREDIT_EXPOSURE
        {
            get
            {
                return this.cREDIT_EXPOSUREField;
            }
            set
            {
                this.cREDIT_EXPOSUREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal CREDIT_LIMIT
        {
            get
            {
                return this.cREDIT_LIMITField;
            }
            set
            {
                this.cREDIT_LIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal CREDIT_LIMIT_USED
        {
            get
            {
                return this.cREDIT_LIMIT_USEDField;
            }
            set
            {
                this.cREDIT_LIMIT_USEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CUSTOMER_NUMBER
        {
            get
            {
                return this.cUSTOMER_NUMBERField;
            }
            set
            {
                this.cUSTOMER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal RECEIVABLES
        {
            get
            {
                return this.rECEIVABLESField;
            }
            set
            {
                this.rECEIVABLESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal SALES_VALUE
        {
            get
            {
                return this.sALES_VALUEField;
            }
            set
            {
                this.sALES_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal SPECIAL_LIABILITIES
        {
            get
            {
                return this.sPECIAL_LIABILITIESField;
            }
            set
            {
                this.sPECIAL_LIABILITIESField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_BAPI_CUSTOMER_CREDITDETAILSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILS Z_BAPI_CUSTOMER_CREDITDETAILS;
        
        public Z_BAPI_CUSTOMER_CREDITDETAILSRequest()
        {
        }
        
        public Z_BAPI_CUSTOMER_CREDITDETAILSRequest(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILS Z_BAPI_CUSTOMER_CREDITDETAILS)
        {
            this.Z_BAPI_CUSTOMER_CREDITDETAILS = Z_BAPI_CUSTOMER_CREDITDETAILS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_BAPI_CUSTOMER_CREDITDETAILSResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse Z_BAPI_CUSTOMER_CREDITDETAILSResponse;
        
        public Z_BAPI_CUSTOMER_CREDITDETAILSResponse1()
        {
        }
        
        public Z_BAPI_CUSTOMER_CREDITDETAILSResponse1(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse Z_BAPI_CUSTOMER_CREDITDETAILSResponse)
        {
            this.Z_BAPI_CUSTOMER_CREDITDETAILSResponse = Z_BAPI_CUSTOMER_CREDITDETAILSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface Z_bapi_customer_detailsChannel : Customer_details.Z_bapi_customer_details, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Z_bapi_customer_detailsClient : System.ServiceModel.ClientBase<Customer_details.Z_bapi_customer_details>, Customer_details.Z_bapi_customer_details
    {
        
        public Z_bapi_customer_detailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse1 Customer_details.Z_bapi_customer_details.Z_BAPI_CUSTOMER_CREDITDETAILS(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest request)
        {
            return base.Channel.Z_BAPI_CUSTOMER_CREDITDETAILS(request);
        }
        
        public Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse Z_BAPI_CUSTOMER_CREDITDETAILS(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILS Z_BAPI_CUSTOMER_CREDITDETAILS1)
        {
            Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest inValue = new Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest();
            inValue.Z_BAPI_CUSTOMER_CREDITDETAILS = Z_BAPI_CUSTOMER_CREDITDETAILS1;
            Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse1 retVal = ((Customer_details.Z_bapi_customer_details)(this)).Z_BAPI_CUSTOMER_CREDITDETAILS(inValue);
            return retVal.Z_BAPI_CUSTOMER_CREDITDETAILSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse1> Customer_details.Z_bapi_customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSAsync(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest request)
        {
            return base.Channel.Z_BAPI_CUSTOMER_CREDITDETAILSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSResponse1> Z_BAPI_CUSTOMER_CREDITDETAILSAsync(Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILS Z_BAPI_CUSTOMER_CREDITDETAILS)
        {
            Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest inValue = new Customer_details.Z_BAPI_CUSTOMER_CREDITDETAILSRequest();
            inValue.Z_BAPI_CUSTOMER_CREDITDETAILS = Z_BAPI_CUSTOMER_CREDITDETAILS;
            return ((Customer_details.Z_bapi_customer_details)(this)).Z_BAPI_CUSTOMER_CREDITDETAILSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
