//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountGetStatutReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS")]
    public interface ZBAPI_CREDIT_ACCOUNT_GETSTATUS
    {
        
        // CODEGEN : La génération du contrat de message depuis l'opération BAPI_CREDIT_ACCOUNT_GET_STATUS n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZBAPI_CREDIT_ACCOUNT_GETSTATUS:BAPI_CREDIT" +
            "_ACCOUNT_GET_STATUSRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1 BAPI_CREDIT_ACCOUNT_GET_STATUS(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZBAPI_CREDIT_ACCOUNT_GETSTATUS:BAPI_CREDIT" +
            "_ACCOUNT_GET_STATUSRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1> BAPI_CREDIT_ACCOUNT_GET_STATUSAsync(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI_CREDIT_ACCOUNT_GET_STATUS
    {
        
        private string cREDITCONTROLAREAField;
        
        private BAPI1010_1[] cREDIT_ACCOUNT_DETAILField;
        
        private BAPI1010_2[] cREDIT_ACCOUNT_OPEN_ITEMSField;
        
        private string cUSTOMERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CREDITCONTROLAREA
        {
            get
            {
                return this.cREDITCONTROLAREAField;
            }
            set
            {
                this.cREDITCONTROLAREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPI1010_1[] CREDIT_ACCOUNT_DETAIL
        {
            get
            {
                return this.cREDIT_ACCOUNT_DETAILField;
            }
            set
            {
                this.cREDIT_ACCOUNT_DETAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPI1010_2[] CREDIT_ACCOUNT_OPEN_ITEMS
        {
            get
            {
                return this.cREDIT_ACCOUNT_OPEN_ITEMSField;
            }
            set
            {
                this.cREDIT_ACCOUNT_OPEN_ITEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CUSTOMER
        {
            get
            {
                return this.cUSTOMERField;
            }
            set
            {
                this.cUSTOMERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI1010_1
    {
        
        private string lOGICAL_SYSField;
        
        private string cUSTMR_NOField;
        
        private string c_CTR_AREAField;
        
        private string cURRENT_PAYER_ONLYField;
        
        private string tIMESTAMPField;
        
        private decimal dUE_ITEMSField;
        
        private string cURRENCY_DIField;
        
        private string cOMP_CODE_DField;
        
        private string cOMPETITOR_DField;
        
        private string dUNN_AREAField;
        
        private string dUNN_LEVELField;
        
        private string dOC_NOField;
        
        private string cOMP_CODE_OOIField;
        
        private string nET_DUE_DATEField;
        
        private string fISC_YEARField;
        
        private string iN_NET_DUE_DATEField;
        
        private string cOMPETITOR_OOIField;
        
        private decimal dAYS_ARREARSField;
        
        private string cURRENCY_OOIField;
        
        private decimal aMOUNT_DOC_CURField;
        
        private decimal cRED_LIMITField;
        
        private string cRED_ACCNTField;
        
        private decimal rCVBL_VALSField;
        
        private decimal cRED_LIABField;
        
        private string cURRENCYField;
        
        private string rISK_CATEGField;
        
        private string bLOCKEDField;
        
        private string nXT_REVIEWField;
        
        private decimal sECURED_ITEMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LOGICAL_SYS
        {
            get
            {
                return this.lOGICAL_SYSField;
            }
            set
            {
                this.lOGICAL_SYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CUSTMR_NO
        {
            get
            {
                return this.cUSTMR_NOField;
            }
            set
            {
                this.cUSTMR_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string C_CTR_AREA
        {
            get
            {
                return this.c_CTR_AREAField;
            }
            set
            {
                this.c_CTR_AREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CURRENT_PAYER_ONLY
        {
            get
            {
                return this.cURRENT_PAYER_ONLYField;
            }
            set
            {
                this.cURRENT_PAYER_ONLYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TIMESTAMP
        {
            get
            {
                return this.tIMESTAMPField;
            }
            set
            {
                this.tIMESTAMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal DUE_ITEMS
        {
            get
            {
                return this.dUE_ITEMSField;
            }
            set
            {
                this.dUE_ITEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CURRENCY_DI
        {
            get
            {
                return this.cURRENCY_DIField;
            }
            set
            {
                this.cURRENCY_DIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string COMP_CODE_D
        {
            get
            {
                return this.cOMP_CODE_DField;
            }
            set
            {
                this.cOMP_CODE_DField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string COMPETITOR_D
        {
            get
            {
                return this.cOMPETITOR_DField;
            }
            set
            {
                this.cOMPETITOR_DField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string DUNN_AREA
        {
            get
            {
                return this.dUNN_AREAField;
            }
            set
            {
                this.dUNN_AREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DUNN_LEVEL
        {
            get
            {
                return this.dUNN_LEVELField;
            }
            set
            {
                this.dUNN_LEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DOC_NO
        {
            get
            {
                return this.dOC_NOField;
            }
            set
            {
                this.dOC_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string COMP_CODE_OOI
        {
            get
            {
                return this.cOMP_CODE_OOIField;
            }
            set
            {
                this.cOMP_CODE_OOIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string NET_DUE_DATE
        {
            get
            {
                return this.nET_DUE_DATEField;
            }
            set
            {
                this.nET_DUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string FISC_YEAR
        {
            get
            {
                return this.fISC_YEARField;
            }
            set
            {
                this.fISC_YEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string IN_NET_DUE_DATE
        {
            get
            {
                return this.iN_NET_DUE_DATEField;
            }
            set
            {
                this.iN_NET_DUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string COMPETITOR_OOI
        {
            get
            {
                return this.cOMPETITOR_OOIField;
            }
            set
            {
                this.cOMPETITOR_OOIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal DAYS_ARREARS
        {
            get
            {
                return this.dAYS_ARREARSField;
            }
            set
            {
                this.dAYS_ARREARSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CURRENCY_OOI
        {
            get
            {
                return this.cURRENCY_OOIField;
            }
            set
            {
                this.cURRENCY_OOIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public decimal AMOUNT_DOC_CUR
        {
            get
            {
                return this.aMOUNT_DOC_CURField;
            }
            set
            {
                this.aMOUNT_DOC_CURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal CRED_LIMIT
        {
            get
            {
                return this.cRED_LIMITField;
            }
            set
            {
                this.cRED_LIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string CRED_ACCNT
        {
            get
            {
                return this.cRED_ACCNTField;
            }
            set
            {
                this.cRED_ACCNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public decimal RCVBL_VALS
        {
            get
            {
                return this.rCVBL_VALSField;
            }
            set
            {
                this.rCVBL_VALSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public decimal CRED_LIAB
        {
            get
            {
                return this.cRED_LIABField;
            }
            set
            {
                this.cRED_LIABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string RISK_CATEG
        {
            get
            {
                return this.rISK_CATEGField;
            }
            set
            {
                this.rISK_CATEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string BLOCKED
        {
            get
            {
                return this.bLOCKEDField;
            }
            set
            {
                this.bLOCKEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string NXT_REVIEW
        {
            get
            {
                return this.nXT_REVIEWField;
            }
            set
            {
                this.nXT_REVIEWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal SECURED_ITEMS
        {
            get
            {
                return this.sECURED_ITEMSField;
            }
            set
            {
                this.sECURED_ITEMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRETURN1
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI1010_2
    {
        
        private string lOGICAL_SYSField;
        
        private string cUSTMR_NOField;
        
        private string c_CTR_AREAField;
        
        private string cURRENT_PAYER_ONLYField;
        
        private decimal nET_ARRERSField;
        
        private string tIMESTAMPField;
        
        private decimal oPEN_ITEMSField;
        
        private string cURRENCYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LOGICAL_SYS
        {
            get
            {
                return this.lOGICAL_SYSField;
            }
            set
            {
                this.lOGICAL_SYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CUSTMR_NO
        {
            get
            {
                return this.cUSTMR_NOField;
            }
            set
            {
                this.cUSTMR_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string C_CTR_AREA
        {
            get
            {
                return this.c_CTR_AREAField;
            }
            set
            {
                this.c_CTR_AREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CURRENT_PAYER_ONLY
        {
            get
            {
                return this.cURRENT_PAYER_ONLYField;
            }
            set
            {
                this.cURRENT_PAYER_ONLYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal NET_ARRERS
        {
            get
            {
                return this.nET_ARRERSField;
            }
            set
            {
                this.nET_ARRERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TIMESTAMP
        {
            get
            {
                return this.tIMESTAMPField;
            }
            set
            {
                this.tIMESTAMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal OPEN_ITEMS
        {
            get
            {
                return this.oPEN_ITEMSField;
            }
            set
            {
                this.oPEN_ITEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI_CREDIT_ACCOUNT_GET_STATUSResponse
    {
        
        private BAPI1010_1[] cREDIT_ACCOUNT_DETAILField;
        
        private BAPI1010_2[] cREDIT_ACCOUNT_OPEN_ITEMSField;
        
        private BAPIRETURN1 rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPI1010_1[] CREDIT_ACCOUNT_DETAIL
        {
            get
            {
                return this.cREDIT_ACCOUNT_DETAILField;
            }
            set
            {
                this.cREDIT_ACCOUNT_DETAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPI1010_2[] CREDIT_ACCOUNT_OPEN_ITEMS
        {
            get
            {
                return this.cREDIT_ACCOUNT_OPEN_ITEMSField;
            }
            set
            {
                this.cREDIT_ACCOUNT_OPEN_ITEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BAPIRETURN1 RETURN
        {
            get
            {
                return this.rETURNField;
            }
            set
            {
                this.rETURNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BAPI_CREDIT_ACCOUNT_GET_STATUSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUS BAPI_CREDIT_ACCOUNT_GET_STATUS;
        
        public BAPI_CREDIT_ACCOUNT_GET_STATUSRequest()
        {
        }
        
        public BAPI_CREDIT_ACCOUNT_GET_STATUSRequest(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUS BAPI_CREDIT_ACCOUNT_GET_STATUS)
        {
            this.BAPI_CREDIT_ACCOUNT_GET_STATUS = BAPI_CREDIT_ACCOUNT_GET_STATUS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse BAPI_CREDIT_ACCOUNT_GET_STATUSResponse;
        
        public BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1()
        {
        }
        
        public BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse BAPI_CREDIT_ACCOUNT_GET_STATUSResponse)
        {
            this.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse = BAPI_CREDIT_ACCOUNT_GET_STATUSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ZBAPI_CREDIT_ACCOUNT_GETSTATUSChannel : AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ZBAPI_CREDIT_ACCOUNT_GETSTATUSClient : System.ServiceModel.ClientBase<AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS>, AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS
    {
        
        public ZBAPI_CREDIT_ACCOUNT_GETSTATUSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress , string username, string password) : 
                base(binding, remoteAddress)
        { /*    ClientCredentials.ServiceCertificate.SslCertificateAuthentication = new System.ServiceModel.Security.X509ServiceCertificateAuthentication
            {
                CertificateValidationMode = System.ServiceModel.Security.X509CertificateValidationMode.None,
                RevocationMode = System.Security.Cryptography.X509Certificates.X509RevocationMode.NoCheck
            };*/
             this.ChannelFactory.Credentials.UserName.UserName = username;
             this.ChannelFactory.Credentials.UserName.Password = password;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1 AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS.BAPI_CREDIT_ACCOUNT_GET_STATUS(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest request)
        {
            return base.Channel.BAPI_CREDIT_ACCOUNT_GET_STATUS(request);
        }
        
        public AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse BAPI_CREDIT_ACCOUNT_GET_STATUS(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUS BAPI_CREDIT_ACCOUNT_GET_STATUS1)
        {
            AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest inValue = new AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest();
            inValue.BAPI_CREDIT_ACCOUNT_GET_STATUS = BAPI_CREDIT_ACCOUNT_GET_STATUS1;
            AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1 retVal = ((AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS)(this)).BAPI_CREDIT_ACCOUNT_GET_STATUS(inValue);
            return retVal.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1> AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS.BAPI_CREDIT_ACCOUNT_GET_STATUSAsync(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest request)
        {
            return base.Channel.BAPI_CREDIT_ACCOUNT_GET_STATUSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSResponse1> BAPI_CREDIT_ACCOUNT_GET_STATUSAsync(AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUS BAPI_CREDIT_ACCOUNT_GET_STATUS)
        {
            AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest inValue = new AccountGetStatutReference.BAPI_CREDIT_ACCOUNT_GET_STATUSRequest();
            inValue.BAPI_CREDIT_ACCOUNT_GET_STATUS = BAPI_CREDIT_ACCOUNT_GET_STATUS;
            return ((AccountGetStatutReference.ZBAPI_CREDIT_ACCOUNT_GETSTATUS)(this)).BAPI_CREDIT_ACCOUNT_GET_STATUSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
