//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ServiceReference1.zBAPI_CUSTOMER_GETLIST")]
    public interface zBAPI_CUSTOMER_GETLIST
    {
        
        // CODEGEN : La génération du contrat de message depuis l'opération BAPI_CUSTOMER_GETLIST n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zBAPI_CUSTOMER_GETLIST:BAPI_CUSTOMER_GETLI" +
            "STRequest", ReplyAction="urn:sap-com:document:sap:rfc:functions:zBAPI_CUSTOMER_GETLIST:BAPI_CUSTOMER_GETLI" +
            "STResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.BAPI_CUSTOMER_GETLISTResponse1 BAPI_CUSTOMER_GETLIST(ServiceReference1.BAPI_CUSTOMER_GETLISTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zBAPI_CUSTOMER_GETLIST:BAPI_CUSTOMER_GETLI" +
            "STRequest", ReplyAction="urn:sap-com:document:sap:rfc:functions:zBAPI_CUSTOMER_GETLIST:BAPI_CUSTOMER_GETLI" +
            "STResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BAPI_CUSTOMER_GETLISTResponse1> BAPI_CUSTOMER_GETLISTAsync(ServiceReference1.BAPI_CUSTOMER_GETLISTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI_CUSTOMER_GETLIST
    {
        
        private BAPICUSTOMER_ADDRESSDATA[] aDDRESSDATAField;
        
        private string cPDONLYField;
        
        private BAPICUSTOMER_IDRANGE[] iDRANGEField;
        
        private int mAXROWSField;
        
        private bool mAXROWSFieldSpecified;
        
        private BAPICUSTOMER_SPECIALDATA[] sPECIALDATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPICUSTOMER_ADDRESSDATA[] ADDRESSDATA
        {
            get
            {
                return this.aDDRESSDATAField;
            }
            set
            {
                this.aDDRESSDATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CPDONLY
        {
            get
            {
                return this.cPDONLYField;
            }
            set
            {
                this.cPDONLYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPICUSTOMER_IDRANGE[] IDRANGE
        {
            get
            {
                return this.iDRANGEField;
            }
            set
            {
                this.iDRANGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int MAXROWS
        {
            get
            {
                return this.mAXROWSField;
            }
            set
            {
                this.mAXROWSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MAXROWSSpecified
        {
            get
            {
                return this.mAXROWSFieldSpecified;
            }
            set
            {
                this.mAXROWSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPICUSTOMER_SPECIALDATA[] SPECIALDATA
        {
            get
            {
                return this.sPECIALDATAField;
            }
            set
            {
                this.sPECIALDATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPICUSTOMER_ADDRESSDATA
    {
        
        private string cUSTOMERField;
        
        private string sORT1Field;
        
        private string nAMEField;
        
        private string cOUNTRYField;
        
        private string cOUNTRYISOField;
        
        private string cITYField;
        
        private string pOSTL_COD1Field;
        
        private string rEGIONField;
        
        private string sTREETField;
        
        private string tEL1_NUMBRField;
        
        private string fAX_NUMBERField;
        
        private string aDDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CUSTOMER
        {
            get
            {
                return this.cUSTOMERField;
            }
            set
            {
                this.cUSTOMERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SORT1
        {
            get
            {
                return this.sORT1Field;
            }
            set
            {
                this.sORT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string COUNTRYISO
        {
            get
            {
                return this.cOUNTRYISOField;
            }
            set
            {
                this.cOUNTRYISOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string POSTL_COD1
        {
            get
            {
                return this.pOSTL_COD1Field;
            }
            set
            {
                this.pOSTL_COD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string REGION
        {
            get
            {
                return this.rEGIONField;
            }
            set
            {
                this.rEGIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string STREET
        {
            get
            {
                return this.sTREETField;
            }
            set
            {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TEL1_NUMBR
        {
            get
            {
                return this.tEL1_NUMBRField;
            }
            set
            {
                this.tEL1_NUMBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string FAX_NUMBER
        {
            get
            {
                return this.fAX_NUMBERField;
            }
            set
            {
                this.fAX_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ADDRESS
        {
            get
            {
                return this.aDDRESSField;
            }
            set
            {
                this.aDDRESSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRETURN1
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPICUSTOMER_SPECIALDATA
    {
        
        private string cUSTOMERField;
        
        private string aCC_1_TIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CUSTOMER
        {
            get
            {
                return this.cUSTOMERField;
            }
            set
            {
                this.cUSTOMERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ACC_1_TIME
        {
            get
            {
                return this.aCC_1_TIMEField;
            }
            set
            {
                this.aCC_1_TIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPICUSTOMER_IDRANGE
    {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OPTION
        {
            get
            {
                return this.oPTIONField;
            }
            set
            {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LOW
        {
            get
            {
                return this.lOWField;
            }
            set
            {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HIGH
        {
            get
            {
                return this.hIGHField;
            }
            set
            {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI_CUSTOMER_GETLISTResponse
    {
        
        private BAPICUSTOMER_ADDRESSDATA[] aDDRESSDATAField;
        
        private BAPICUSTOMER_IDRANGE[] iDRANGEField;
        
        private BAPIRETURN1 rETURNField;
        
        private BAPICUSTOMER_SPECIALDATA[] sPECIALDATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPICUSTOMER_ADDRESSDATA[] ADDRESSDATA
        {
            get
            {
                return this.aDDRESSDATAField;
            }
            set
            {
                this.aDDRESSDATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPICUSTOMER_IDRANGE[] IDRANGE
        {
            get
            {
                return this.iDRANGEField;
            }
            set
            {
                this.iDRANGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BAPIRETURN1 RETURN
        {
            get
            {
                return this.rETURNField;
            }
            set
            {
                this.rETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPICUSTOMER_SPECIALDATA[] SPECIALDATA
        {
            get
            {
                return this.sPECIALDATAField;
            }
            set
            {
                this.sPECIALDATAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BAPI_CUSTOMER_GETLISTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ServiceReference1.BAPI_CUSTOMER_GETLIST BAPI_CUSTOMER_GETLIST;
        
        public BAPI_CUSTOMER_GETLISTRequest()
        {
        }
        
        public BAPI_CUSTOMER_GETLISTRequest(ServiceReference1.BAPI_CUSTOMER_GETLIST BAPI_CUSTOMER_GETLIST)
        {
            this.BAPI_CUSTOMER_GETLIST = BAPI_CUSTOMER_GETLIST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BAPI_CUSTOMER_GETLISTResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ServiceReference1.BAPI_CUSTOMER_GETLISTResponse BAPI_CUSTOMER_GETLISTResponse;
        
        public BAPI_CUSTOMER_GETLISTResponse1()
        {
        }
        
        public BAPI_CUSTOMER_GETLISTResponse1(ServiceReference1.BAPI_CUSTOMER_GETLISTResponse BAPI_CUSTOMER_GETLISTResponse)
        {
            this.BAPI_CUSTOMER_GETLISTResponse = BAPI_CUSTOMER_GETLISTResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface zBAPI_CUSTOMER_GETLISTChannel : ServiceReference1.zBAPI_CUSTOMER_GETLIST, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class zBAPI_CUSTOMER_GETLISTClient : System.ServiceModel.ClientBase<ServiceReference1.zBAPI_CUSTOMER_GETLIST>, ServiceReference1.zBAPI_CUSTOMER_GETLIST
    {
        
        public zBAPI_CUSTOMER_GETLISTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress, string username, string password) : 
                base(binding, remoteAddress)
        {
           /* ClientCredentials.ServiceCertificate.SslCertificateAuthentication = new System.ServiceModel.Security.X509ServiceCertificateAuthentication
            {
                CertificateValidationMode = System.ServiceModel.Security.X509CertificateValidationMode.None,
                RevocationMode = System.Security.Cryptography.X509Certificates.X509RevocationMode.NoCheck
            };*/
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.BAPI_CUSTOMER_GETLISTResponse1 ServiceReference1.zBAPI_CUSTOMER_GETLIST.BAPI_CUSTOMER_GETLIST(ServiceReference1.BAPI_CUSTOMER_GETLISTRequest request)
        {
            return base.Channel.BAPI_CUSTOMER_GETLIST(request);
        }
        
        public ServiceReference1.BAPI_CUSTOMER_GETLISTResponse BAPI_CUSTOMER_GETLIST(ServiceReference1.BAPI_CUSTOMER_GETLIST BAPI_CUSTOMER_GETLIST1)
        {
            ServiceReference1.BAPI_CUSTOMER_GETLISTRequest inValue = new ServiceReference1.BAPI_CUSTOMER_GETLISTRequest();
            inValue.BAPI_CUSTOMER_GETLIST = BAPI_CUSTOMER_GETLIST1;
            ServiceReference1.BAPI_CUSTOMER_GETLISTResponse1 retVal = ((ServiceReference1.zBAPI_CUSTOMER_GETLIST)(this)).BAPI_CUSTOMER_GETLIST(inValue);
            return retVal.BAPI_CUSTOMER_GETLISTResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.BAPI_CUSTOMER_GETLISTResponse1> ServiceReference1.zBAPI_CUSTOMER_GETLIST.BAPI_CUSTOMER_GETLISTAsync(ServiceReference1.BAPI_CUSTOMER_GETLISTRequest request)
        {
            return base.Channel.BAPI_CUSTOMER_GETLISTAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BAPI_CUSTOMER_GETLISTResponse1> BAPI_CUSTOMER_GETLISTAsync(ServiceReference1.BAPI_CUSTOMER_GETLIST BAPI_CUSTOMER_GETLIST)
        {
            ServiceReference1.BAPI_CUSTOMER_GETLISTRequest inValue = new ServiceReference1.BAPI_CUSTOMER_GETLISTRequest();
            inValue.BAPI_CUSTOMER_GETLIST = BAPI_CUSTOMER_GETLIST;
            return ((ServiceReference1.zBAPI_CUSTOMER_GETLIST)(this)).BAPI_CUSTOMER_GETLISTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
